[workspace]
members = [
    "crates/zkdb-merkle",
    "crates/zkdb-core",
    "crates/zkdb-lib",
    "crates/script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
rs_merkle = "1.4.2"
prettytable-rs = "0.10"