[package]
version = "0.1.0"
name = "zkdb-merkle"
edition = "2021"

[dependencies]
sp1-zkvm = "2.0.0"
rs_merkle = { version = "1.4.2", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
bincode = { version = "1.3", default-features = false }