[package]
name = "zkdb-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
zkdb-core = { path = "../zkdb-core" }
sp1-sdk = { version = "2.0.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
bincode = "1.3"
clap = "2.33"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"
