name: Rust CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-20.04
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUST_BACKTRACE: "1"
      SP1_PATH: "/home/runner/.sp1"
      RUSTUP_HOME: "/home/runner/.rustup"

    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0
          components: clippy, rustfmt

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up
          echo "$SP1_PATH/bin" >> $GITHUB_PATH

      - name: Verify SP1 installation
        run: |
          cargo prove --version

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        env:
          CARGO_INCREMENTAL: 1
        with:
          command: check
          args: --all-targets
